#
b C:\totvs\
#
d "Schema Area":6,32;1 C:\totvs\
#
d "Employee":7,32;1 C:\totvs\ f 320
d "Employee":7,32;1 C:\totvs\
#
d "Inventory":8,32;1 C:\totvs\ f 640
d "Inventory":8,32;1 C:\totvs\
#
d "Cust_Data":9,32;1 C:\totvs\ f 320
d "Cust_Data":9,32;1 C:\totvs\
#
d "Cust_Index":10,32;1 C:\totvs\ f 320
d "Cust_Index":10,32;1 C:\totvs\
#
d "Order":11,32;1 C:\totvs\ f 1280
d "Order":11,32;1 C:\totvs\
#
d "Misc":12,32;1 C:\totvs\ f 320
d "Misc":12,32;1 C:\totvs\
